"""add_sync_log

Revision ID: 012b56a386d1
Revises: 540272dec2c4
Create Date: 2026-03-20 20:34:31.160491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012b56a386d1'
down_revision: Union[str, Sequence[str], None] = '540272dec2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_client_id'), 'sync_logs', ['client_id'], unique=True)
    op.create_index(op.f('ix_sync_logs_entity'), 'sync_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_sync_logs_record_id'), 'sync_logs', ['record_id'], unique=False)
    op.create_table('raw_material_price_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_price_history_material_id'), 'raw_material_price_history', ['material_id'], unique=False)
    op.create_index(op.f('ix_raw_material_price_history_recorded_at'), 'raw_material_price_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_material_price_history_recorded_at'), table_name='raw_material_price_history')
    op.drop_index(op.f('ix_raw_material_price_history_material_id'), table_name='raw_material_price_history')
    op.drop_table('raw_material_price_history')
    op.drop_index(op.f('ix_sync_logs_record_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_entity'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_client_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
