"""add_manufacturing_bom_and_raw_materials

Revision ID: 1677f3d1084c
Revises: 47141285382d
Create Date: 2026-03-20 12:40:30.320058

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1677f3d1084c"
down_revision: Union[str, Sequence[str], None] = "47141285382d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bom_item_id"), table_name="bom")
    op.drop_table("bom")
    op.create_table(
        "bill_of_materials",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("required_qty", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("wastage_pct", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["raw_materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bill_of_materials_item_id"),
        "bill_of_materials",
        ["item_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_price_history_material_id"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_recorded_at"), table_name="price_history")
    op.drop_table("price_history")
    op.add_column(
        "items",
        sa.Column("production_cost", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "raw_materials",
        sa.Column("stock", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "raw_materials", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "raw_materials",
        "current_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_raw_materials_name"), table_name="raw_materials")
    op.create_index(
        op.f("ix_raw_materials_name"), "raw_materials", ["name"], unique=True
    )
    op.drop_column("raw_materials", "stock_quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_materials",
        sa.Column(
            "stock_quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_raw_materials_name"), table_name="raw_materials")
    op.create_index(
        op.f("ix_raw_materials_name"), "raw_materials", ["name"], unique=False
    )
    op.alter_column(
        "raw_materials",
        "current_price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("raw_materials", "created_at")
    op.drop_column("raw_materials", "stock")
    op.drop_column("items", "production_cost")
    op.create_table(
        "price_history",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("material_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "recorded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["raw_materials.id"],
            name=op.f("price_history_material_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("price_history_pkey")),
    )
    op.create_index(
        op.f("ix_price_history_recorded_at"),
        "price_history",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_history_material_id"),
        "price_history",
        ["material_id"],
        unique=False,
    )
    op.create_table(
        "bom",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("item_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("material_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "wastage_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("bom_item_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["raw_materials.id"], name=op.f("bom_material_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("bom_pkey")),
    )
    op.drop_index(op.f("ix_bill_of_materials_item_id"), table_name="bill_of_materials")
    op.drop_table("bill_of_materials")
    op.create_index(op.f("ix_bom_item_id"), "bom", ["item_id"], unique=False)
    # ### end Alembic commands ###
