"""system_hardening_sync_prep

Revision ID: 540272dec2c4
Revises: cf27a2149e8a
Create Date: 2026-03-20 19:36:44.256336

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "540272dec2c4"
down_revision: Union[str, Sequence[str], None] = "cf27a2149e8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attendance", sa.Column("client_id", sa.UUID(), nullable=True))
    op.add_column("attendance", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_attendance_client_id"), "attendance", ["client_id"], unique=True
    )
    op.create_index(
        op.f("ix_attendance_recorded_by"), "attendance", ["recorded_by"], unique=False
    )
    op.add_column(
        "bill_of_materials", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "bill_of_materials", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_bill_of_materials_material_id"),
        "bill_of_materials",
        ["material_id"],
        unique=False,
    )
    op.add_column("items", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "raw_materials", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("sale_items", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("sale_items", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "sale_items",
        "price_at_sale",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sale_items",
        "gst_percent",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "cgst_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "sgst_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "total_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_sale_items_item_id"), "sale_items", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_sale_items_sale_id"), "sale_items", ["sale_id"], unique=False
    )
    op.add_column("sales", sa.Column("client_id", sa.UUID(), nullable=True))
    op.add_column("sales", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "sales",
        "sub_total",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "tax_total",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "discount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "total_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_sales_client_id"), "sales", ["client_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_client_id"), table_name="sales")
    op.alter_column(
        "sales",
        "total_amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "discount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "tax_total",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sales",
        "sub_total",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("sales", "updated_at")
    op.drop_column("sales", "client_id")
    op.drop_index(op.f("ix_sale_items_sale_id"), table_name="sale_items")
    op.drop_index(op.f("ix_sale_items_item_id"), table_name="sale_items")
    op.alter_column(
        "sale_items",
        "total_price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "sgst_amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "cgst_amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "gst_percent",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "sale_items",
        "price_at_sale",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("sale_items", "updated_at")
    op.drop_column("sale_items", "created_at")
    op.drop_column("raw_materials", "updated_at")
    op.drop_column("items", "updated_at")
    op.drop_index(
        op.f("ix_bill_of_materials_material_id"), table_name="bill_of_materials"
    )
    op.drop_column("bill_of_materials", "updated_at")
    op.drop_column("bill_of_materials", "created_at")
    op.drop_index(op.f("ix_attendance_recorded_by"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_client_id"), table_name="attendance")
    op.drop_column("attendance", "updated_at")
    op.drop_column("attendance", "client_id")
    # ### end Alembic commands ###
