"""increase_bom_precision_to_4_decimal_places

Revision ID: 583dd7a99482
Revises: 1677f3d1084c
Create Date: 2026-03-20 13:21:18.583340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "583dd7a99482"
down_revision: Union[str, Sequence[str], None] = "1677f3d1084c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bill_of_materials",
        "required_qty",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
    )
    op.alter_column(
        "bill_of_materials",
        "wastage_pct",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bill_of_materials",
        "wastage_pct",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "bill_of_materials",
        "required_qty",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
