"""add workforce module and update user wage

Revision ID: cf27a2149e8a
Revises: 583dd7a99482
Create Date: 2026-03-20 19:01:39.968940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf27a2149e8a'
down_revision: Union[str, Sequence[str], None] = '583dd7a99482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('daily_wage', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('attendance', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('attendance', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendance', 'recorded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.drop_column('attendance', 'wage_rate_override')
    op.drop_column('attendance', 'check_in')
    op.drop_column('attendance', 'check_out')
    op.add_column('daily_wages', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('daily_wages', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('daily_wages', 'attendance_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('daily_wages', 'amount')
    op.add_column('users', sa.Column('base_daily_wage', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_daily_wage')
    op.add_column('daily_wages', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('daily_wages', 'attendance_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('daily_wages', 'paid_at')
    op.drop_column('daily_wages', 'total_amount')
    op.add_column('attendance', sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('wage_rate_override', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.alter_column('attendance', 'recorded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendance', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('attendance', 'created_at')
    op.drop_column('attendance', 'payment_status')
    op.drop_column('attendance', 'daily_wage')
    # ### end Alembic commands ###
