from abc import ABC, abstractmethod
from typing import Any
from uuid import UUID


class BaseRepository(ABC):
    """
    Abstract interface for the Repository pattern.

    Represents a collection-oriented interface for accessing domain objects.
    """

    @abstractmethod
    def get_by_id(self, record_id: UUID) -> Any:
        """
        Retrieve a single entity by its primary key ID.

        Args:
            record_id (UUID): Unique ID of the record.

        Returns:
            Any: The domain entity if found, else None.
        """

    @abstractmethod
    def get_by_id_scoped(self, record_id: UUID, user_id: UUID) -> Any:
        """
        Retrieve an entity belonging to a specific user.

        Args:
            record_id (UUID): Unique ID of the record.
            user_id (UUID): ID of the owner user.

        Returns:
            Any: The domain entity if found and authorized, else None.
        """

    @abstractmethod
    def add(self, entity: Any) -> None:
        """
        Add a new entity to the repository.

        Args:
            entity (Any): The domain object to persist.
        """

    @abstractmethod
    def update(self, entity: Any) -> None:
        """
        Notify the repository that an entity has been modified.

        Args:
            entity (Any): The modified domain object.
        """

    @abstractmethod
    def delete(self, entity: Any) -> None:
        """
        Remove an entity from the repository.

        Args:
            entity (Any): The domain object to delete.
        """

    @abstractmethod
    def get_by_client_id(self, client_id: str) -> Any:
        """
        Search for an entity by its client-generated ID (idempotency).

        Args:
            client_id (str): The unique ID generated by the client.

        Returns:
            Any: The existing domain entity if found.
        """


class AbstractUnitOfWork(ABC):
    """
    Interface for the Unit of Work pattern.

    Coordinates the atomic commit of multiple repository operations
    and manages the database transaction boundary.
    """

    items: BaseRepository
    sales: BaseRepository
    attendance: BaseRepository
    raw_materials: BaseRepository
    sync_logs: BaseRepository
    users: BaseRepository
    customers: BaseRepository
    wages: BaseRepository
    purchases: BaseRepository
    purchase_items: BaseRepository
    # Day 1 additions
    orders: BaseRepository
    production_jobs: BaseRepository
    job_assignments: BaseRepository

    def __enter__(self) -> "AbstractUnitOfWork":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type:
            self.rollback()

    @property
    @abstractmethod
    def session(self):
        pass

    @abstractmethod
    def commit(self):
        pass

    @abstractmethod
    def rollback(self):
        pass

    @abstractmethod
    def flush(self):
        pass

    @abstractmethod
    def refresh(self, entity: Any):
        pass

    @abstractmethod
    def begin_nested(self):
        pass
